#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.11"
# dependencies = ["rich>=13"]
# ///
"""
Criterion benchmark report for rsx-dxs protocol comparison.

Usage:
    uv run scripts/bench_report.py                  # all benches in target/criterion/
    uv run scripts/bench_report.py --filter compare # only compare_* benches
    uv run scripts/bench_report.py --md             # also write REPORT.md
    uv run scripts/bench_report.py --md --out rsx-dxs/compare/RESULTS.md
"""

import argparse
import json
import sys
from pathlib import Path

from rich.console import Console
from rich.table import Table

ROOT = Path(__file__).parent.parent
CRITERION = ROOT / "target" / "criterion"

# Known benchmarks from the compare_* suite, in display order.
# Anything not listed is appended alphabetically at the end.
PROTOCOL_ORDER = [
    "raw_udp_64b",
    "kcp_rtt_spin_flush",
    "kcp_spin_flush_64b",
    "kcp_rtt_naive_1ms_interval",
    "quinn_rtt_persistent_64b",
    "quinn_persistent_64b",
    "quinn_rtt_new_stream_64b",
    "tcp_rtt_nodelay_64b",
    "tcp_nodelay_64b",
]

LABELS = {
    "raw_udp_64b":              "raw UDP",
    "kcp_rtt_spin_flush":       "KCP spin+flush",
    "kcp_spin_flush_64b":       "KCP spin+flush (all)",
    "kcp_rtt_naive_1ms_interval":"KCP naive 1ms",
    "quinn_rtt_persistent_64b": "QUIC persistent",
    "quinn_persistent_64b":     "QUIC persistent (all)",
    "quinn_rtt_new_stream_64b": "QUIC new-stream",
    "tcp_rtt_nodelay_64b":      "TCP nodelay",
    "tcp_nodelay_64b":          "TCP nodelay (all)",
}


def fmt_ns(ns: float) -> str:
    if ns < 1_000:
        return f"{ns:.0f} ns"
    if ns < 1_000_000:
        return f"{ns / 1_000:.1f} µs"
    return f"{ns / 1_000_000:.2f} ms"


def load_results(filter_str: str | None) -> list[dict]:
    if not CRITERION.exists():
        print(f"[error] {CRITERION} not found — run 'cargo bench' first", file=sys.stderr)
        sys.exit(1)

    results = []
    for est_path in sorted(CRITERION.glob("*/new/estimates.json")):
        name = est_path.parts[-3]  # target/criterion/<name>/new/estimates.json
        if filter_str and filter_str.lower() not in name.lower():
            continue
        data = json.loads(est_path.read_text())
        mean_ns = data["mean"]["point_estimate"]
        lo_ns   = data["mean"]["confidence_interval"]["lower_bound"]
        hi_ns   = data["mean"]["confidence_interval"]["upper_bound"]
        std_ns  = data["std_dev"]["point_estimate"]
        results.append({
            "name":    name,
            "label":   LABELS.get(name, name),
            "mean_ns": mean_ns,
            "lo_ns":   lo_ns,
            "hi_ns":   hi_ns,
            "std_ns":  std_ns,
        })

    order = {k: i for i, k in enumerate(PROTOCOL_ORDER)}
    results.sort(key=lambda r: (order.get(r["name"], 999), r["mean_ns"]))
    return results


def render_rich(results: list[dict]) -> None:
    console = Console()
    t = Table(title="Protocol RTT comparison (64B payload, loopback)", show_lines=False)
    t.add_column("Protocol",   style="bold cyan",  no_wrap=True)
    t.add_column("Mean RTT",   style="bold green",  justify="right")
    t.add_column("±σ",                              justify="right")
    t.add_column("95% CI",                          justify="right")

    baseline = results[0]["mean_ns"] if results else 1.0
    for r in results:
        ratio = r["mean_ns"] / baseline
        ratio_str = "" if ratio < 1.05 else f"  [dim]{ratio:.0f}×[/dim]"
        ci = f"{fmt_ns(r['lo_ns'])} – {fmt_ns(r['hi_ns'])}"
        t.add_row(
            r["label"] + ratio_str,
            fmt_ns(r["mean_ns"]),
            fmt_ns(r["std_ns"]),
            ci,
        )

    console.print()
    console.print(t)
    console.print()


def render_md(results: list[dict], out_path: Path) -> None:
    lines = [
        "# Protocol RTT comparison",
        "",
        "Payload: 64 bytes, loopback, Criterion n=50.",
        "",
        "| Protocol | Mean RTT | ±σ | vs baseline |",
        "|----------|----------|----|-------------|",
    ]
    baseline = results[0]["mean_ns"] if results else 1.0
    for r in results:
        ratio = r["mean_ns"] / baseline
        ratio_str = "1×" if ratio < 1.05 else f"{ratio:.0f}×"
        lines.append(
            f"| {r['label']} | {fmt_ns(r['mean_ns'])} | {fmt_ns(r['std_ns'])} | {ratio_str} |"
        )
    lines += ["", "_Generated by `scripts/bench_report.py`._", ""]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path.relative_to(ROOT)}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Criterion RTT report for compare_* benches")
    ap.add_argument("--filter", default=None, metavar="STR",
                    help="only include benchmarks whose name contains STR")
    ap.add_argument("--md", action="store_true",
                    help="also write a markdown table")
    ap.add_argument("--out", default="rsx-dxs/compare/RESULTS.md", metavar="PATH",
                    help="markdown output path (default: rsx-dxs/compare/RESULTS.md)")
    args = ap.parse_args()

    results = load_results(args.filter)
    if not results:
        print("no benchmark results found", file=sys.stderr)
        sys.exit(1)

    render_rich(results)

    if args.md:
        render_md(results, ROOT / args.out)


if __name__ == "__main__":
    main()
